import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowRight,Bot,Check,ChevronDown,Code2,Database,Globe2,Menu,MessageCircle,Send,ShieldCheck,Smartphone,Sparkles,Workflow,BarChart3,Building2,X,Zap}from"lucide-react";import"./styles.css";
const C={email:"jdinfynixsolutions@gmail.com",phone:"+91 7676336768",wa:"917676336768",domain:"jdinfynixsolutions.in"};
const services=[
["Business Websites","Fast, responsive websites that make your business look credible and convert visitors into enquiries.","From ₹5,000",Globe2],
["Custom Web Applications","Secure web apps, portals and internal systems built around your business workflow.","From ₹20,000",Code2],
["CRM & Business Systems","Manage leads, customers, follow-ups and operations from one simple dashboard.","From ₹15,000",Database],
["Billing & Inventory","Practical billing, invoicing, stock and reporting solutions for growing businesses.","From ₹10,000",BarChart3],
["Mobile Applications","Modern apps designed for customers, teams and field operations.","From ₹25,000",Smartphone],
["AI & Automation","Automate repetitive work and connect tools with AI where it creates real value.","Custom quote",Bot]
];
const solutions=["Lead & customer management","Billing & invoice workflows","Inventory & stock tracking","School & student management","Appointment & booking systems","WhatsApp automation","Business dashboards & reports","Custom portals & internal tools"];
const industries=["Restaurants & cafés","Clinics & healthcare businesses","Schools & coaching centres","Real-estate businesses","Transport & logistics","Small manufacturers","Retail & local shops","Professional services"];
const faqs=[
["Do you build custom software?","Yes. We build custom websites, web applications, dashboards, CRM, billing, inventory, automation and mobile applications around your requirements."],
["Can you work with a small business?","Absolutely. Our solutions are designed for small and growing businesses, with practical starting solutions that can expand later."],
["How do I get a quotation?","Send your requirement through WhatsApp or the project form. We will review the requirement and discuss the scope before giving a quote."],
["Do you provide AI and automation?","Yes. We identify repetitive workflows and build AI-assisted or automated processes where they create real business value."]
];
const wa=m=>window.open(`https://wa.me/${C.wa}?text=${encodeURIComponent(m)}`,"_blank","noopener,noreferrer");
function App(){const[open,setOpen]=useState(false),[faq,setFaq]=useState(0),[form,setForm]=useState({name:"",business:"",phone:"",message:""});const go=id=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};const submit=e=>{e.preventDefault();wa(`Hello JD INFYNIX SOLUTIONS,\n\nName: ${form.name}\nBusiness: ${form.business}\nPhone: ${form.phone}\nProject: ${form.message}`)};return <div>
<header><div className="container nav"><a className="brand" href="#home"><span className="mark">JD</span><span><b>INFYNIX</b><small>SOLUTIONS</small></span></a><nav className={open?"open":""}>{["Services","Solutions","Process","About","Contact"].map(x=><button key={x} onClick={()=>go(x.toLowerCase())}>{x}</button>)}<button className="navcta" onClick={()=>go("contact")}>Start a Project <ArrowRight size={16}/></button></nav><button className="menub" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
<section id="home" className="hero"><div className="container herogrid"><div><span className="eyebrow">SOFTWARE • AI • AUTOMATION</span><h1>Build smarter.<br/><em>Grow faster.</em></h1><p className="lead">Digital solutions for businesses that want to work better, serve customers faster and scale with confidence.</p><div className="actions"><button className="primary" onClick={()=>go("contact")}>Discuss Your Project <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go("services")}>Explore Solutions</button></div><div className="trust"><span><ShieldCheck/>Business-focused <b>Solutions</b></span><span><Zap/>Fast & scalable <b>Technology</b></span><span><MessageCircle/>Direct <b>WhatsApp</b></span></div></div>
<div className="visual"><div className="dash"><div className="dashhead"><span>● SYSTEM ONLINE</span><span>JD / INFYNIX</span></div><h3>Business Command Center</h3><div className="metrics"><div><small>LEADS</small><b>1,284</b><i>↗ 18.4%</i></div><div><small>AUTOMATION</small><b>92%</b><i>↗ 12.7%</i></div><div><small>RESPONSE</small><b>2.4m</b><i>↘ 31.2%</i></div></div><div className="chart">{[35,55,45,72,60,80,68,94].map((h,i)=><span key={i} style={{height:h+"%"}}/> )}</div><div className="dashfoot"><span><Bot size={15}/> AI Automation</span><span><Workflow size={15}/> Connected workflows</span></div></div><div className="float a"><Sparkles/><b>AI Ready</b><small>Automate repetitive work</small></div><div className="float b"><Check/><b>Built for business</b><small>Simple. Practical. Scalable.</small></div></div></div></section>
<div className="stats"><div className="container statsgrid">{[["06+","Core solution areas"],["08+","Business industries"],["100%","Custom to your workflow"],["24/7","Digital availability"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div>
<section id="services" className="section"><div className="container"><div className="sectionhead"><div><span className="kicker">WHAT WE BUILD</span><h2>Technology that solves <em>real problems.</em></h2></div><p>From your first website to a complete business operating system, we build practical digital products around your goals.</p></div><div className="servicegrid">{services.map(([t,d,p,I])=><article className="service" key={t}><div className="icon"><I/></div><h3>{t}</h3><p>{d}</p><footer><b>{p}</b><button onClick={()=>wa(`Hello JD INFYNIX SOLUTIONS, I am interested in ${t}. Please share details.`)}><ArrowRight/></button></footer></article>)}</div></div></section>
<section id="solutions" className="section dark"><div className="container solgrid"><div className="code"><div>JD_INFYNIX / WORKFLOW <span>● LIVE</span></div><pre>{`const business = {\n  leads: "centralized",\n  billing: "automated",\n  inventory: "tracked",\n  customers: "connected",\n  ai: "integrated"\n};\n\ndeploy(business);\n// ready to scale ✓`}</pre><small>› system.optimize()</small></div><div><span className="kicker">ONE PARTNER. MANY SOLUTIONS.</span><h2>Turn scattered work into <em>one connected system.</em></h2><p>We combine websites, software, automation and AI so your business tools work together instead of creating more work.</p><div className="sollist">{solutions.map(x=><span key={x}><Check size={16}/>{x}</span>)}</div><button className="primary" onClick={()=>go("contact")}>Plan My Solution <ArrowRight size={18}/></button></div></div></section>
<section id="process" className="section"><div className="container"><div className="center"><span className="kicker">HOW WE WORK</span><h2>From idea to <em>launch.</em></h2><p>A clear process with no unnecessary complexity.</p></div><div className="processgrid">{[["01","Discover","We understand your business, customers, workflow and goals."],["02","Design","We map the experience and create a clean interface around your users."],["03","Build","We develop, connect required services and test important workflows."],["04","Launch & Improve","We help you go live and continue improving as your business grows."]].map(x=><div className="process" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
<section className="industry"><div className="container"><div className="center"><span className="kicker">BUILT FOR GROWING BUSINESSES</span><h2>Your industry. <em>Your workflow.</em></h2><p>We adapt technology to your business instead of forcing your business to adapt to software.</p></div><div className="industrygrid">{industries.map((x,i)=><div key={x}><small>0{i+1}</small><Building2 size={18}/><b>{x}</b><ArrowRight size={16}/></div>)}</div></div></section>
<section id="about" className="section about"><div className="container aboutgrid"><div><span className="kicker">ABOUT JD INFYNIX SOLUTIONS</span><h2>A technology partner focused on <em>business outcomes.</em></h2></div><div><p>JD INFYNIX SOLUTIONS helps small and growing businesses move from manual processes to modern digital systems.</p><p>Our approach is simple: understand the problem first, choose the right technology, keep the experience easy to use and build for the next stage of growth.</p><div className="points"><span><Check/>Clear communication</span><span><Check/>Practical solutions</span><span><Check/>Modern technology</span><span><Check/>Scalable foundations</span></div></div></div></section>
<section className="section faqsec"><div className="container faqgrid"><div><span className="kicker">FAQ</span><h2>Questions before <em>we start?</em></h2><p>Tell us what you are trying to build. We can start with a simple conversation and turn it into a clear project plan.</p></div><div>{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setFaq(faq===i?-1:i)}>{q}<ChevronDown/></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
<section id="contact" className="contact"><div className="container contactgrid"><div><span className="kicker">LET'S BUILD</span><h2>Have a project in mind?</h2><p>Tell us what you need. Whether it is a website, business software, mobile app or automation, start with a simple message.</p><div className="details"><a href={`mailto:${C.email}`}><Send/>{C.email}</a><a href={`tel:${C.phone.replaceAll(" ","")}`}><Smartphone/>{C.phone}</a><button onClick={()=>wa("Hello JD INFYNIX SOLUTIONS, I want to discuss a software project.")}><MessageCircle/>Chat on WhatsApp</button></div></div><form onSubmit={submit}><h3>Start your enquiry <small>Replies on WhatsApp</small></h3><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><div className="two"><label>Business<input value={form.business} onChange={e=>setForm({...form,business:e.target.value})} placeholder="Your business"/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+91..."/></label></div><label>What do you want to build?<textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Website, CRM, billing software, mobile app, AI automation..."/></label><button className="primary full">Send Enquiry on WhatsApp <ArrowRight size={18}/></button></form></div></section>
<footer className="foot"><div className="container footgrid"><div><a className="brand" href="#home"><span className="mark">JD</span><span><b>INFYNIX</b><small>SOLUTIONS</small></span></a><p>Software, AI & automation solutions for modern businesses.</p></div><div><b>Explore</b><button onClick={()=>go("services")}>Services</button><button onClick={()=>go("solutions")}>Solutions</button><button onClick={()=>go("about")}>About</button></div><div><b>Contact</b><a href={`mailto:${C.email}`}>{C.email}</a><a href={`tel:${C.phone.replaceAll(" ","")}`}>{C.phone}</a><button onClick={()=>wa("Hello JD INFYNIX SOLUTIONS.")}>WhatsApp</button></div></div><div className="container copy">© {new Date().getFullYear()} JD INFYNIX SOLUTIONS <span>{C.domain}</span></div></footer><button className="wafloat" onClick={()=>wa("Hello JD INFYNIX SOLUTIONS, I would like to discuss a project.")}><MessageCircle/><span>WhatsApp</span></button>
</div>}
createRoot(document.getElementById("root")).render(<App/>);